# Generated by Django 4.0.4 on 2022-05-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
